import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between px-6 py-4">
          <Link href="/" className="font-semibold">X-index</Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link href="/leaderboard" className="opacity-80 hover:opacity-100">Leaderboard</Link>
            <Link href="/api/auth/signin" className="opacity-80 hover:opacity-100">Sign in</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
